spring:
  application:
    name: discovery

server:
  port: 8888

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka
